# Terraform Backend Configuration
# Generated by InfraLLM on 2025-12-18T16:13:54.388474

terraform {
  backend "s3" {
    bucket         = "your-organization-terraform-state"
    key            = "staging/s3/staging-app-logs-bucket/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "your-organization-terraform-locks"
  }
}
