# S3 Bucket: staging-app-logs-bucket
# Environment: staging
# Generated by InfraLLM on 2025-12-18T16:13:54.388474

resource "aws_s3_bucket" "staging_app_logs_bucket" {
  bucket = "staging-app-logs-bucket"

  tags = {    Environment = "staging"    Application = "app"    CostCenter = "engineering"    Owner = "platform-team"    ManagedBy = "terraform"  }
}

# Bucket versioning configuration
resource "aws_s3_bucket_versioning" "staging_app_logs_bucket" {
  bucket = aws_s3_bucket.staging_app_logs_bucket.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Server-side encryption configuration
resource "aws_s3_bucket_server_side_encryption_configuration" "staging_app_logs_bucket" {
  bucket = aws_s3_bucket.staging_app_logs_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Public access block configuration
resource "aws_s3_bucket_public_access_block" "staging_app_logs_bucket" {
  bucket = aws_s3_bucket.staging_app_logs_bucket.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
# Lifecycle configuration
resource "aws_s3_bucket_lifecycle_configuration" "staging_app_logs_bucket" {
  bucket = aws_s3_bucket.staging_app_logs_bucket.id  rule {
    id     = "expire-old-logs"
    status = "Enabled"    expiration {
      days = 60
    }  }}