# Input Variables for S3 Bucket: staging-app-logs-bucket
# Generated by InfraLLM on 2025-12-18T16:13:54.388474

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "staging"
}

variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default = {    Environment = "staging"    Application = "app"    CostCenter = "engineering"    Owner = "platform-team"    ManagedBy = "terraform"  }
}
