# Terraform Backend Configuration
# Generated by InfraLLM on 2025-12-18T16:06:01.187761

terraform {
  backend "s3" {
    bucket         = "your-organization-terraform-state"
    key            = "dev/s3/dev-pr-automation-bucket/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "your-organization-terraform-locks"
  }
}
