# S3 Bucket: dev-pr-automation-bucket
# Environment: dev
# Generated by InfraLLM on 2025-12-18T16:06:01.187761

resource "aws_s3_bucket" "dev_pr_automation_bucket" {
  bucket = "dev-pr-automation-bucket"

  tags = {    Environment = "dev"    Application = "pr-automation"    CostCenter = "engineering"    Owner = "platform-team"    ManagedBy = "terraform"    Phase = "4"  }
}

# Bucket versioning configuration
resource "aws_s3_bucket_versioning" "dev_pr_automation_bucket" {
  bucket = aws_s3_bucket.dev_pr_automation_bucket.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Server-side encryption configuration
resource "aws_s3_bucket_server_side_encryption_configuration" "dev_pr_automation_bucket" {
  bucket = aws_s3_bucket.dev_pr_automation_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Public access block configuration
resource "aws_s3_bucket_public_access_block" "dev_pr_automation_bucket" {
  bucket = aws_s3_bucket.dev_pr_automation_bucket.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
# Lifecycle configuration
resource "aws_s3_bucket_lifecycle_configuration" "dev_pr_automation_bucket" {
  bucket = aws_s3_bucket.dev_pr_automation_bucket.id  rule {
    id     = "expire-test-data"
    status = "Enabled"    expiration {
      days = 30
    }  }}