# Outputs for S3 Bucket: dev-pr-automation-bucket
# Generated by InfraLLM on 2025-12-18T16:06:01.187761

output "bucket_id" {
  description = "The name of the bucket"
  value       = aws_s3_bucket.dev_pr_automation_bucket.id
}

output "bucket_arn" {
  description = "The ARN of the bucket"
  value       = aws_s3_bucket.dev_pr_automation_bucket.arn
}

output "bucket_domain_name" {
  description = "The bucket domain name"
  value       = aws_s3_bucket.dev_pr_automation_bucket.bucket_domain_name
}

output "bucket_regional_domain_name" {
  description = "The bucket region-specific domain name"
  value       = aws_s3_bucket.dev_pr_automation_bucket.bucket_regional_domain_name
}
