# Input Variables for S3 Bucket: dev-pr-automation-bucket
# Generated by InfraLLM on 2025-12-18T16:06:01.187761

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default = {    Environment = "dev"    Application = "pr-automation"    CostCenter = "engineering"    Owner = "platform-team"    ManagedBy = "terraform"    Phase = "4"  }
}
